import { PlannerState } from "./model";
export const seed: PlannerState = {
  trips: [
    {
      id: "autumn",
      image: "/tokyo.jpg",
      title: "A little Tokyo, a lot of live music",
      cities: "Tokyo · Yokohama",
      start: "2026-10-09",
      end: "2026-10-13",
      status: "Confirmed",
      notes:
        "Five days, three stages. Leave some time for record shops in Shimokitazawa.",
    },
    {
      id: "winter",
      title: "Osaka, one more time",
      cities: "Osaka",
      start: "2026-12-04",
      end: "2026-12-07",
      status: "Tentative",
      notes: "A winter weekend built around the next show.",
    },
  ],
  concerts: [
    {
      id: "idol",
      image: "/concert-stage.jpg",
      title: "THE IDOLM@STER",
      subtitle: "星のきらめき · Autumn Live",
      date: "2026-10-10",
      time: "17:00",
      venue: "Tokyo Garden Theater",
      city: "Tokyo",
      zone: "Asia/Tokyo",
      tripId: "autumn",
      color: "blue",
      notes:
        "Doors open at 16:00. Bring photo ID and check the ticket collection instructions.",
    },
    {
      id: "love",
      image: "/concert-stage.jpg",
      title: "Love Live!",
      subtitle: "Our next chapter · Live in Yokohama",
      date: "2026-10-11",
      time: "18:00",
      venue: "K Arena Yokohama",
      city: "Yokohama",
      zone: "Asia/Tokyo",
      tripId: "autumn",
      color: "pink",
      notes: "Sample performance. Result needs to be checked manually.",
    },
    {
      id: "uma",
      image: "/concert-stage.jpg",
      title: "Uma Musume",
      subtitle: "Twinkle together · Special live",
      date: "2026-10-12",
      time: "16:30",
      venue: "Ariake Arena",
      city: "Tokyo",
      zone: "Asia/Tokyo",
      tripId: "autumn",
      color: "mint",
      notes: "Ticket is paid. Collection is available.",
    },
    {
      id: "equal",
      image: "/concert-stage.jpg",
      title: "=LOVE",
      subtitle: "Winter notes · 大阪公演",
      date: "2026-12-06",
      time: "",
      venue: "Osaka-jō Hall",
      city: "Osaka",
      zone: "Asia/Tokyo",
      tripId: "winter",
      color: "peach",
      notes: "",
    },
    {
      id: "wish",
      title: "いつか、またあのステージで",
      subtitle: "A concert to look forward to",
      date: "",
      time: "",
      venue: "To be announced",
      city: "Japan",
      zone: "Asia/Tokyo",
      tripId: "",
      color: "lilac",
      notes: "Wishlist — no announced date yet.",
    },
  ],
  applications: [
    {
      id: "a1",
      concertId: "idol",
      round: "Fanclub advance lottery",
      provider: "ASOBI TICKET",
      deadline: "2026-09-20T14:59:00Z",
      resultDate: "2026-09-27T03:00:00Z",
      paymentDeadline: "2026-10-01T09:00:00Z",
      submitted: true,
      result: "Won",
      payment: "Unpaid",
      collection: "Not ready",
      amount: 12000,
      currency: "JPY",
      reminder: true,
      offset: "2 hours",
    },
    {
      id: "a2",
      concertId: "idol",
      round: "General advance lottery",
      provider: "eplus",
      deadline: "2026-10-02T14:59:00Z",
      resultDate: "2026-10-04T03:00:00Z",
      paymentDeadline: "",
      submitted: false,
      result: "Pending",
      payment: "Not required",
      collection: "Not ready",
      amount: 12000,
      currency: "JPY",
      reminder: false,
      offset: "1 day",
    },
    {
      id: "a3",
      concertId: "love",
      round: "Official advance lottery",
      provider: "l-tike",
      deadline: "2026-09-23T14:59:00Z",
      resultDate: "2026-10-01T03:00:00Z",
      paymentDeadline: "2026-10-03T12:00:00Z",
      submitted: true,
      result: "Pending",
      payment: "Unpaid",
      collection: "Not ready",
      amount: 11000,
      currency: "JPY",
      reminder: true,
      offset: "1 day",
    },
    {
      id: "a4",
      concertId: "uma",
      round: "Reserved seat",
      provider: "CyStore ticket",
      deadline: "2026-09-20T14:59:00Z",
      resultDate: "2026-09-22T03:00:00Z",
      paymentDeadline: "",
      submitted: true,
      result: "Won",
      payment: "Paid",
      collection: "Ready",
      amount: 9800,
      currency: "JPY",
      reminder: true,
      offset: "1 day",
    },
  ],
  hotels: [
    {
      id: "h1",
      tripId: "autumn",
      name: "The Tokyo Stay",
      city: "Shinjuku, Tokyo",
      checkIn: "2026-10-09",
      checkOut: "2026-10-11",
      cancellation: "2026-10-02T09:00:00Z",
      amount: 28000,
      currency: "JPY",
      payment: "Paid",
      reference: "DEMO-TYO-2410",
    },
    {
      id: "h2",
      tripId: "autumn",
      name: "Harbor House Yokohama",
      city: "Minatomirai, Yokohama",
      checkIn: "2026-10-11",
      checkOut: "2026-10-13",
      cancellation: "",
      amount: 26000,
      currency: "JPY",
      payment: "Unpaid",
      reference: "DEMO-YKH-1310",
    },
  ],
  deliveries: [],
  preferences: {
    zone: "Asia/Singapore",
    currency: "JPY",
    theme: "light",
    solid: false,
    destination: "dm",
    connected: false,
    channel: "my-concert-plans",
    revealTitle: false,
  },
};
